This is a testharness.js-based test.
Harness Error. harness_status.status = 2 , harness_status.message = 
[FAIL] No CORS fetch after a redirect with an URL containing credentials
  promise_test: Unhandled rejection with value: object "TypeError: Failed to fetch"
[FAIL] CORS fetch after a redirect with a same origin URL containing credentials
  promise_test: Unhandled rejection with value: object "TypeError: Failed to fetch"
[FAIL] Image loading after a redirect with an URL containing credentials
  promise_test: Unhandled rejection with value: object "[object Event]"
[FAIL] CORS Image loading after a redirect with a same origin URL containing credentials
  promise_test: Unhandled rejection with value: object "[object Event]"
[TIMEOUT] Frame loading after a redirect with an URL containing credentials
  Test timed out
Harness: the test ran to completion.
